### ISSUE TITLE
The character sort will not load.

### ISSUE THREAD

**Issue by Dememenic** [execfera/charasort#21]
I'm opening the index.html locally on my computer and when I click on the button to load it, the sort won't load at all. Nothing happens when I click the load button. I've verified within the index.html and data.js that everything is fine with no errors.

**Comment by JNRU** [comment]
Literally impossible to run it locally, has to be hosted somewhere.

**Comment by Dememenic** [comment]
Yeah I figured that 2 years ago.. My bad.

**Comment by JNRU** [comment]
Sorry man, was just trying to bait some 'um actually' guy to show up and prove me wrong by posting details, but i'm pretty sure this is abandoned anyway
